/* Описание формата шрифта:

         1. Массив font_data[] содержит:
            - Битовый поток пикселей всех глифов
            - Биты упакованы по строкам, слева направо, сверху вниз
            - Бит 0 = пиксель отсутствует (фон), бит 1 = пиксель присутствует (символ)

         2. Массив glyphs[] содержит структуры с информацией о каждом символе:
            - ascii_code: код символа (может быть в cp1251 для русских букв)
            - width: ширина символа в пикселях  
            - bit_offset: смещение в битах от начала массива font_data до первого пикселя символа

         3. Структура font_descriptor содержит:
            - указатели на данные шрифта и глифов
            - размеры и количество символов
            - высоту шрифта

         Принцип формирования битового потока:
         - Биты идут последовательно: слева направо, сверху вниз для каждого символа
         - Бит 0 соответствует левому верхнему пикселю символа
         - Байты в массиве содержат по 8 бит, бит 7 первого байта - это бит 7, 
           бит 0 второго байта - это бит 8 от начала потока и т.д.

         Пример: символ шириной 5 пикселей, высотой 8 пикселей занимает 5*8=40 бит = 5 байт
         Биты 0-4: первая строка (слева направо)
         Биты 5-9: вторая строка (слева направо)
         ... и так далее
        */
        
// Font: spleen-5x8, Height: 8px
// Generated by Python font rasterizer
// Total glyphs: 10



        #ifndef SSD_1306_FONT_DESCR
        #define SSD_1306_FONT_DESCR

        typedef struct 
        {
            unsigned char ascii_code;
            unsigned char width;
            unsigned short bit_offset;
        } glyphs_t;

        typedef struct
        {
            const unsigned char * font_data;
            const glyphs_t * glyphs;
            uint16_t font_data_size;
            uint8_t glyphs_num;
            uint8_t font_height;
        } font_descriptor_t;

        #endif //SSD_1306_FONT_DESCR
        
static const unsigned char font_data_spleen_5x8[] = {
    0xC0, 0xA4, 0xB6, 0x92, 0x01, 0x80, 0x18, 0x42, 0x88, 0x03, 0xC0, 0x24, 0x64, 0xC2, 0x03, 0xC0, 
    0x24, 0x82, 0x92, 0x01, 0x20, 0x94, 0xF2, 0x08, 0x01, 0xE0, 0x85, 0x83, 0xD0, 0x01, 0xC0, 0x84, 
    0x93, 0x92, 0x01, 0xE0, 0x25, 0x44, 0x84, 0x00, 0xC0, 0x24, 0x93, 0x92, 0x01, 0xC0, 0xA4, 0xE4, 
    0x90, 0x01
};

static const glyphs_t glyphs_spleen_5x8[] = {
    { 0x30, 5, 0 }, // '0'
    { 0x31, 5, 40 }, // '1'
    { 0x32, 5, 80 }, // '2'
    { 0x33, 5, 120 }, // '3'
    { 0x34, 5, 160 }, // '4'
    { 0x35, 5, 200 }, // '5'
    { 0x36, 5, 240 }, // '6'
    { 0x37, 5, 280 }, // '7'
    { 0x38, 5, 320 }, // '8'
    { 0x39, 5, 360 }, // '9'
};

static const font_descriptor_t font_spleen_5x8 = {
    font_data_spleen_5x8,
    glyphs_spleen_5x8,
    50,  // font_data_size
    10,  // glyphs_num
    8  // font_height
};

